name: Minimal Workflow Test

on: [push]
#
jobs:
    run-selenium-script:
      runs-on: ubuntu-latest
  
      container:
        image: selenium/standalone-chrome
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Run minimal Selenium script
          run: python minimal_selenium.py