name: Selenium Script

on:
  push:
    branches:
      - main  # Assuming 'main' is your default branch, change if necessary
  schedule:
    # Runs at 23:00 UTC (6 PM Miami time without daylight saving)
    - cron: '0 23 * * *'

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    container: 
      image: selenium/standalone-chrome

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium script
      run: python script.py
