name: Selenium Script

on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 23:00 UTC every dayy
    - cron: '0 23 * * *'

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    container: 
      image: selenium/standalone-chrome

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Update this to the latest version

    - name: Set up Python
      uses: actions/setup-python@v3 # Update this to the latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium script
      run: python script.py
